title: Guillermo Vizcaíno Román
logo: /Foto-carnet.png
email: guillevzn@gmail.com
description: Data Analyst
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: Curriculum Vitae
    icon: <svg xmlns="https://upload.wikimedia.org/wikipedia/commons/9/97/Document_icon_%28the_Noun_Project_27904%29.svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://guillevzn.github.io/cv.html
  - name: LinkedIn
    icon: fa-brands fa-linkedin
    link: https://www.linkedin.com/in/guillevzn/
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/guillevzn
  - name: Twitter
    icon: fa-brands fa-twitter
    link: https://twitter.com/guillevzn
