title: Guillermo Vizcaíno Román
logo: /Foto-carnet.jpg
email: gvizroman@gmail.com
description: Analista Económico
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: LinkedIn
    icon: fa-solid fa-linked-in
    link: https://www.linkedin.com/in/gvizroman/
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/guilleviz
  - name: Twitter
    icon: fa-brands fa-twitter
    link: https://twitter.com/vizcainoguille
