title: Guillermo Vizcaíno Román
logo: /Foto-CV.png
email: guillevzn@gmail.com
description: Data Analyst
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: Curriculum Vitae
    icon: fa-solid fa-file
    link: https://guillevzn.github.io/cv.html
  - name: LinkedIn
    icon: fa-brands fa-linkedin
    link: https://www.linkedin.com/in/guillevzn/
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/guillevzn
